### ISSUE TITLE
iesafe option does not work

### ISSUE THREAD

**Issue by alex-shamshurin** [bhovhannes/svg-url-loader#127]
I think it's an option to load all svg with size > 4rb with file-loader. But it doesnt' work.  

```
 {
        test: /\.svg/,
        use: {
          loader: 'svg-url-loader',
          options: {
            iesafe: true
          }
        }
      },

```

**Comment by EECOLOR** [comment]
If you look at the [source code](https://github.com/bhovhannes/svg-url-loader/blob/master/index.js#L31), it has an additional requirement: your content needs to have a `style` tag.

**Comment by alex-shamshurin** [comment]
No matter, IE11 does not work with `class`. It must not be inlined to support IE11. This option should fix it without conditions.

**Comment by bhovhannes** [comment]
@kgram, as an author of `iesafe` option, do you have any thoughts on this?

**Comment by kgram** [comment]
@alex-shamshurin: I don't understand what aspect of classes you would expect to work without a style-tag. Is the problem internal references to masks or something?

I wasn't aware of any broken features besides style-tags, so I made a check to avoid unnecessary bailouts. In my defense, I did document it under the option description ("[..]if the file contains a style-element and the encoded size is above 4kB[..]"). Can you possibly post an example of an SVG that doesn't work (possibly with path-data removed if it's sensitive, hopefully the problem will still be visible)? It's possible the style-tag check should just be removed to be completely safe.

**Comment by kgram** [comment]
@alex-shamshurin: just a little ping, if you can describe in more detail what the problem is, I'd be happy to take a look at it.

**Comment by shikelong** [comment]
[leyserPlusLogo.zip](https://github.com/bhovhannes/svg-url-loader/files/1517253/leyserPlusLogo.zip)

hi, @kgram  The svg has style tag, but in ie11, it's has been convert to inline data-url svg and only has black color. I expect it fallback to fileloader.

The loader option:

```js
{
        test: /\.(svg)$/,
        use: [{
          loader: 'svg-url-loader',
          options: {
            limit: 10000,
            iesafe: true,
            encoding: 'base64'
          }
        }]
      },

```

Regards.

**Comment by kgram** [comment]
I had expected some sort of weird IE behaviour when using base64, but it turned out to be plain stupidity from myself. When I wrote the feature I forgot that `.` in regex does't match line breaks. All my generated examples are without extra whitespace and everywhere I use the loader myself I have it placed after an optimiser that strips the extra whitespace, so I've never noticed it.

I'm sorry for any trouble my oversight has caused. The good news is that until a new release is ready the problem should be fixable by placing an optimiser-loader such as [svgo-loader](https://www.npmjs.com/package/svgo-loader) before the svg-url-loader.
