### ISSUE TITLE
why do I have to specify noquotes here but not in url-loader?

### ISSUE THREAD

**Issue by fringd** [bhovhannes/svg-url-loader#151]
I am using some svgs in css and some in img tags... I don't know how uncommon this use case is.

It seems I need `noquotes` to make images work, but that breaks css...

Why is this a problem in svg-url-loader, but not a problem in url-loader?

I love the smaller payload, but i'm temporarily back on url-loader until I can figure this out.

**Comment by QoVoQ** [comment]
Meet the same problem, looking for a solution.
While setting `noquotes: true`,
` // woubld be invalid if bg.svg is tranformed into inline svg`
`.bg { background: url('~images/bg.svg') }`

`<img src="~images/bg.svg" // would be valid in this case`

Otherwise, setting  `noquotes: false`
` // woubld be valid if bg.svg is tranformed into inline svg`
`.bg { background: url('~images/bg.svg') }`

`<img src="~images/bg.svg" // would be invalid in this case`

**Comment by bhovhannes** [comment]
Guys, you need to specify `noquotes` option in image case and do not specify it in css case.
You have to explicitly override loader options in order to achieve that.

But that way you'll have 2 separate images in your bundle. Perhaps it will be better to use url-loader in terms of smaller bundle size...

**Comment by QoVoQ** [comment]
Thanks for your attention.@bhovhannes
So you suggest us use url-loader? But I don't want inline svg base64 encoded.

**Comment by bhovhannes** [comment]
@QoVoQ in your example you've mentioned the same image - bg.svg used in 2 different ways. In that case url-loader will give you a smaller bundle size, because bg.svg will be included only once in the final bundle.
In order to use svg-url-loader, you should tell webpack to use `noquotes` parameter in one case and not to use in the other one. It is totally possible.

**Comment by fringd** [comment]
Is there any webpage configuration that will apply the noquotes=true only
for img tags? Or do you need to do this every time?

**Comment by bhovhannes** [comment]
@fringd , you have to explicitly pass `noquotes` option every time for each `img` tag

**Comment by fringd** [comment]
Oh I think I tried this, but it would end up double encoding.

**Comment by bhovhannes** [comment]
Are you using double "!" in front of file name? That will tell webpack to
ignore all existing loaders for that kind of file and use only loader
you've explicitly specified.

**Comment by fringd** [comment]
No I didn't know about that!

**Comment by danielduan** [comment]
you can also use webpack resource queries to determine which loader option you want to use for a given file extension.

```
{
  test: /\.svg$/,
  oneOf: [
    {
      resourceQuery: /css/,
      use: "svg-url-loader",
    },
    {
      resourceQuery: /js/,
      use: {
        loader: "svg-url-loader",
        options: {
          noquotes: true
        }
      }
    },
  ],
},
```
