### ISSUE TITLE
Is there a way to load the value of SVG into a variable?

### ISSUE THREAD

**Issue by gajus** [bhovhannes/svg-url-loader#29]
I need to post-process the value of SVG in SASS.

Use case is defined here, http://stackoverflow.com/a/33435726/368691.

Is there a way to load the SVG as a string into SASS variable?

In effect, it would need to generate a code that looks like this:

```sass
$circle-icon-svg: '<svg xmlns="http://www.w3.org/2000/svg"><circle cx="10" cy="10" r="10" /></svg>';
```

I am assuming that `sass` loader runs after `svg-url-loader`. Is that a correct assumption?

**Comment by bhovhannes** [comment]
@gajus, in your use case you need unmodified source of SVG image.
This loader by design encodes SVG source so it can be used in data-uri scheme.
So, I think it will not be useful in described situation.

You may want to try [raw-loader](https://github.com/webpack/raw-loader) webpack loader to get SVG contents as a string.

**Comment by gajus** [comment]
Understood.
