### ISSUE TITLE
[Proposal] Union `svg-url-loader` with `url-loader`.

### ISSUE THREAD

**Issue by evilebottnawi** [bhovhannes/svg-url-loader#91]
Be great have one awesome loader. I am a member of `webpack-contrib` and can help with this. Your will also remain the main contributor. I asked about this in `webpack-contrib` slack channel and give :+1: from main contributors `webpack/webpack-contrib`. What do your think about this?

**Comment by bhovhannes** [comment]
In general I am ok with that. However we should discuss the details. Where is the correct place for such discussion?

**Comment by evilebottnawi** [comment]
@bhovhannes good news! https://webpack.slack.com/messages/C3NUYSYF4/, just ping me

**Comment by bhovhannes** [comment]
@evilebottnawi, can you send me an invite for webpack slack team? I think I need it to sign in...

**Comment by evilebottnawi** [comment]
@bhovhannes oh sorry, gave the wrong link https://webpack.slack.com/messages/C1LUX2DS9/ :smile: or we can `discussion` about this here, if you are comfortable

**Comment by bhovhannes** [comment]
@evilebottnawi I cannot sign in to webpack team on slack, because I don't have an account there. So, let's speak here. Please bring in any people from `webpack/webpack-contrib` you feel it will be nice to participate in discussion.

Here is how I see the current differences between svg-url-loader and url-loader.
1. My plan for `svg-url-loader` is to add option to minimize imported SVGs using SVGO.
2. `svg-url-loader` has tests, which run on Travis automatically.
3. `svg-url-loader` repo is greenkeeper enabled.

Regarding 1. 
That can be implemented in a separate loader and these 2 loaders may work in tandem, but minimizing is so common task that I think it will be better to have it built-in in the `svg-url-loader`.
I am not sure if minimizing SVGs is something `url-loader` should do.

Regarding 2.
Tests should be added to `url-loader` as well. Only after testing infrastructure will be ready we can start merge of `svg-url-loader`.

Regarding 3.
I cannot enable greenkeeper on `url-loader`, as I am not an admin of `webpack/webpack-contrib`. I will miss its PRs.

I think separate issues should be opened for each of mentioned points in `url-loader` repo in order to proceed effectively. @evilebottnawi, what do you think?

**Comment by evilebottnawi** [comment]
@bhovhannes 

> My plan for `svg-url-loader` is to add option to minimize imported SVGs using SVGO. 

Sounds good, each loader can works in `minify` mode. But `url-loader` handle not only `svg` and maybe it is be related to `compress/compress-images/image/imagemin-loader`. This would keep the compression options (for `imagemin`) in one place, but we can think about this more and we can will find to a common decision. Now we can `https://github.com/Klathmon/imagemin-webpack-plugin` (not good solution because for this purpose best be `loader`, but some plugins, example `CopyWebpackPlugin` can copying image also, `svg` also, this will be a small overload if `svg-url/url-loader` will do it) and `https://github.com/tcoopman/image-webpack-loader`(It seems to be outdated and have weird name, best for me `imagemin/compress-image-loader` - this `loader` don't load images, just compress), i have own solution https://github.com/itgalaxy/imagemin-webpack (have loader and plugin for both purposes). 

> `svg-url-loader` has tests, which run on Travis automatically.

No problems, in many our loader exists test and they run on `travis` automatically. And we should to write tests for him, we just sometimes do not have time for all this :sob: 

> `svg-url-loader` repo is greenkeeper enabled. 

`greenkeeper` in now not very `smart` bot, `sub bad true`, but i'm sure that this will not be a problem, perhaps this will be the beginning to correct his behavior and enable (enable again in some repo :smile: )

/cc @michael-ciniawsky

**Comment by michael-ciniawsky** [comment]
@bhovhannes @evilebottnawi 👋 

> 1. My plan for svg-url-loader is to add option to minimize imported SVGs using SVGO.

This would be better as a separate loader chained with `url-loader` then 😛 

> 2. `svg-url-loader` has tests, which run on Travis automatically

WIP

> 3. `svg-url-loader` repo is greenkeeper enabled

We handle all majot deps in webpack-contrib (`loader-utils`, `schema-utils` (Options Validation)) && are actively maintaining the 'core' loaders


Long story short, we could add an `encoding` option to `url-loader`  and optimisations (generic or webpack related) like  this loader currently does with the `content`replacement part could be done aswell depending on the MIME type

The reason for this is mainly to avoid the already existing UX problems many folks have with webpack today, since picking the right `loader/plugin` is hard (especially for beginners). Some unification effort would be highly appreciated.

**Comment by bhovhannes** [comment]
@michael-ciniawsky 

> 1. My plan for svg-url-loader is to add option to minimize imported SVGs using SVGO.

There is [svgo-loader](https://github.com/rpominov/svgo-loader) which seems to does exactly what I was intended to do here, so that point is not so important at this moment.

> 2. svg-url-loader has tests, which run on Travis automatically

Can Travis CI be enabled on url-loader? What can I do from my side to help with that?

> 3. svg-url-loader repo is greenkeeper enabled

Can you (or someone else) enable greenkeeper on `url-loader` repo? What can I do from my side to help with that?

> Long story short, we could add an encoding option to url-loader and optimisations (generic or webpack related) like this loader currently does with the contentreplacement part could be done aswell depending on the MIME type

What can I do from my side? Should I put together a PR which will bring in the functionality to `url-loader`?

**Comment by evilebottnawi** [comment]
@bhovhannes Yep, PR is be good decision. Let's do PR :+1: 

> Can Travis CI be enabled on url-loader? What can I do from my side to help with that?

Also do in PR.

> Can you (or someone else) enable greenkeeper on url-loader repo? What can I do from my side to help with that?

In discussion into PR we can find solution for this, maybe not a bad idea to enable `greenkeeper` for this repo and see how correctly their now works.

**Comment by evilebottnawi** [comment]
@bhovhannes You can do this step-by-step:

1. Add functionality.
2. Add tests.
3. Enable greenkeeper.
4. ...
5. PROFIT!

**Comment by d3viant0ne** [comment]
@bhovhannes - I'm afraid everyone has gotten ahead of themselves. A few things right out of the gate.

- This needs to be discussed by the webpack-contrib owners. 
- There are legal considerations as we are a part of the JavaScript Foundation.
- We do not nor will we ever use Greenkeeper in contrib.
- This discussion will be moved over to https://github.com/webpack-contrib/organization/issues where it should have been to begin with.
- The idea in whatever final form will be discussed and if it makes sense for both groups wither myself or @bebraw will get in touch.

**Comment by evilebottnawi** [comment]
Close issue here, if someone want this union please recreate issue here https://github.com/webpack-contrib/organization, thanks for everyone!

**Comment by bhovhannes** [comment]
@evilebottnawi after the last comment of @d3viant0ne whole process seems unnecessarily complicated to me.
At this moment I have little time to dedicate to open-source, and if I will I'd better spend it to address some long standing issues here. 
So, speaking shortly, no.

**Comment by evilebottnawi** [comment]
@bhovhannes we implement `decoder` option for `url-loader` so all what you do loader now possible do with `url-loader`, so i think you can be champion of decoder.
